sudo: required
services:
  - docker

before_install:
  - docker build -t dhananjay12/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dhananjay12/react-test npm test -- --coverage

after_success:
  - docker build -t dhananjay12/multi-client ./client
  - docker build -t dhananjay12/multi-nginx ./nginx
  - docker build -t dhananjay12/multi-server ./server
  - docker build -t dhananjay12/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dhananjay12/multi-client
  - docker push dhananjay12/multi-nginx
  - docker push dhananjay12/multi-server
  - docker push dhananjay12/multi-worker
